server:
  port: 9000

spring:
  application:
    name: Cards microservice
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:h2:mem:cards
    username: sa
    password: ""
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console